//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_gallery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    public partial class Image
    {
        public int ImageId { get; set; }
        public string ImagePath { get; set; }
       // [DisplayName("Upload File")]
        public string Geolocation { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> Captured_date { get; set; }
        public string Captured_by { get; set; }
        [DisplayName("Upload File")]
        public HttpPostedFileBase ImageFile {get; set;}
    }
}
